### PR TITLE
psychometric validity tool with cronbach's alpha

### PR DESCRIPTION
**Pull request by DaveBuckingham**
Mainly a response to #15. Happy to make any needed changes. I have no idea how it does on large inputs, just using the stuff in /examples. If needed I could switch it to numpy or pandas. If this goes well probably the next step would be to add more features e.g. try to do omega.

### CODE REVIEW

**Comment by njvack** [comment]
Dang, yo, thanks! I had literally no idea anyone was using this outside our center.

I'm not 100% sold on renaming `measure` to `aggregator` — yes, it's a better name but also I am not excited about breaking existing scoresheets. I guess `aggregator` could be the new canonical name with `measure` also accepted? (Maybe that's already the implementation; I have not had time to experiment.)

`aggregate` / `aggregation` might be better than `aggregator`?

I'm okay if this doesn't work on giant inputs; this for "human-scale" data. Adding numpy / pandas as a dependency might make sense; at that point we'd probably want to change a lot of implementation stuff.

If we're going to bring omega into the mix, we'll certainly want numpy (and maybe scipy and/or other numerical libraries) — my sense is that that one is a pretty mathy lift.

Per-subject reliability (Mahalanobis distance, even-odd concurrence, etc)... can't really go in this `reliability` tool, right? This makes a one-thing-per-aggregator kind of reliability measurement, the other ones are per-subject. But notably, they also often depend on data from other subjects, so I don't know that they belong in score_data, either.

Hm. Anyhow, that's just an aside.

If scoresheets using `measure` continue to work, I'm happy with this. Thoughts on `aggregate` versus `aggregator`?

**Comment by DaveBuckingham** [comment]
Oh yeah It shouldn't break any existing scoresheets: it still expects keyword "measure" in the scoresheets, the change is just internal i.e. variable names and such. Sure if folks wanted to write "aggregate(/or)" on the scoresheets then probably the best way would be for the parser to allow either. Sorry I'm new to this field and don't really understand the question about per-subject reliability. I think that any reliability metric that can be computed from the input data could be appropriate and possible to include. An obvious next step would be to recompute alpha with each question removed.

**Comment by njvack** [comment]
haha "parser"

There are two fundamentally kinds of "reliability" measures — one, like alpha and omega, asks "is this measure behaving as an internally consistent thing?" so you'd get one value out per aggregation.

The other (Mahalanobis distance, etc) basically tries to get at "is this participant jerking us around?" and so you get a value per participant.

Anyhow okay if this doesn't affect scoresheet construction I'm happy to merge this; I do think adding "aggregate" as a synonym for "measure" in scoresheets would be a good call, I think it's a clearer term. I'm gonna roll it around a little more before committing to that though

**Comment by njvack** [comment]
fwiw I am also not expert in this field ;-)

**Comment by njvack** [comment]
aw man this broke CI

**Comment by DaveBuckingham** [comment]
sorry, what is CI?

**Comment by DaveBuckingham** [comment]
OK sorry about that. I figured out how to use flake8 to find and fix that specific problem. Is there anything else I should do to make sure CI will work before resubmitting e.g. can i find what tests the CI will do so I can run them locally first? Sorry, new at this.

**Comment by njvack** [comment]
Yup: https://github.com/uwmadison-chm/scorify/blob/main/.github/workflows/pythonpackage.yml

I'm not super good at CI either — in an ideal world it would have run checks on your PR automatically; I don't know why it didn't

**Pull request merged**
